[tool.poetry]
name = "jovian-careers-website"
version = "0.1.0"
description = ""
authors = ["Shico-2129 <bushico212@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
